# Generated by Django 5.2.17 on 2026-09-17 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='请输入有效的手机号。', regex='^\\+?[0-9]{6,20}$')], verbose_name='手机号'),
        ),
    ]
