# Generated by Django 5.2.17 on 2026-09-17 07:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise_type', models.CharField(choices=[('walking', '快走'), ('running', '跑步'), ('strength', '力量训练'), ('other', '其他')], max_length=16)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('intensity', models.CharField(choices=[('easy', '轻松'), ('moderate', '中等'), ('hard', '较累')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '加餐')], max_length=16)),
                ('food', models.TextField()),
                ('portion', models.CharField(blank=True, max_length=200)),
                ('fullness', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('photo_url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('weight', '体重'), ('waist', '腰围')], max_length=12)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='StrengthSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=120)),
                ('sets', models.PositiveSmallIntegerField()),
                ('reps_per_set', models.PositiveSmallIntegerField()),
                ('load_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_sets', to='tracker.exercise')),
            ],
            options={
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('weekly_exercise_minutes', models.PositiveIntegerField(default=150)),
                ('weekly_strength_sessions', models.PositiveSmallIntegerField(default=2)),
                ('show_calories', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['user', 'occurred_at'], name='tracker_exe_user_id_aee2dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='exercise_duration_positive'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['user', 'occurred_at'], name='tracker_mea_user_id_0cf293_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['user', 'occurred_at'], name='tracker_mea_user_id_6498f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='measurement_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='strengthset',
            constraint=models.CheckConstraint(condition=models.Q(('sets__gt', 0)), name='strength_sets_positive'),
        ),
        migrations.AddConstraint(
            model_name='strengthset',
            constraint=models.CheckConstraint(condition=models.Q(('reps_per_set__gt', 0)), name='strength_reps_positive'),
        ),
        migrations.AddConstraint(
            model_name='strengthset',
            constraint=models.UniqueConstraint(fields=('exercise', 'order'), name='strength_exercise_order_unique'),
        ),
    ]
