# Generated by Django 5.2.17 on 2026-09-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_exercise_user_alter_meal_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strengthset',
            options={'ordering': ('exercise', 'order')},
        ),
        migrations.RemoveConstraint(
            model_name='strengthset',
            name='strength_exercise_order_unique',
        ),
    ]
